enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1


[Tiktok]
apkmirror-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/tik-tok-including-musical-ly-38-2-2-release/tiktok-38-2-2-android-apk-download/"
included-patches = "'SIM spoof'"
